---
title: "Why Prompt-Learner?"
---
We are practitioners and researchers ourselves and we keep running into the same problem again and again of writing a new prompt string from scratch, and then optmizing and maintaing it over time. \
We believe that a prompt in itself is too big a unit and too critical a piece of the puzzle to not be broken down into simpler meaningful parts. \
We also believe that swapping in and swapping out different alternatives for these modular parts of a prompt in a systematic and optimization centric paradigm will lead to optmized, maintainable and more understandable prompting.\
There is no systematic and simple tool that allows users to control the granular parts of a prompt and optimize it, and we want to solve this problem with prompt-learner. \

## Focus Areas of Prompt-Learner

Prompt Learner focuses on two aspects of prompting - 

1. Converting a prompt from a single string(or fstring) to well defined modular parts that can eventually be *assembled* to create the eventual prompt.
2. Enable users to programatically modify, replace, mix and match different alternatives in each module of the prompt to *optimize* the final prompt for performance. 

## Community

We are building a community of developers who believe that prompting is here to stay, and are excited about tinkering with it programatically and systematically. Join our [discord](https://discord.gg/FST9HRNKYX). \

For discussions, issues and requests regarding the library, join us on [GitHub](https://github.com/attuna-xyz/prompt-learner/discussions)

## Getting started

If you're interested in trying Prompt-learner we recommend the [getting started
tutorial](./tutorials/getting_started.qmd).
